name: Bug 反馈 (Bug Feedback)
description: 提交一个 issue 帮助改进这个项目 (Submit an issue to help improve this project)
title: "[Bug] 在这里输入你的标题 (Enter your title here)"
labels: ["bug"]
assignees:
  - teamssix
body:
- type: markdown
  attributes:
    value: |
      感谢您花时间提交这份 issue (Thanks for taking the time to fill out this bug report! )
- type: textarea
  id: what-happened
  attributes:
    label: 描述你遇到的问题 (What happened?)
    value: "详细描述你所遇到的问题 (Describe in detail the problem you are experiencing.)"
  validations:
    required: true
- type: textarea
  attributes:
    label: 复现步骤 (Steps To Reproduce)
    description: 复现这个问题的步骤 (Steps to reproduce the behavior.)
    placeholder: |
      1. 在 xxx 情况下 (in the xxx case)
      2. 执行了 xxx 命令 (executed the xxx command)
      3. 出现了 xxx 错误 (an xxx error occurred)
  validations:
    required: true
- type: dropdown
  id: system
  attributes:
    label: 操作系统 (Operating System)
    description: 你在哪个操作系统下运行的 CF ？(Which operating system you are running the CF in?)
    options:
      - MacOS
      - Linux
      - Windows
  validations:
    required: true
- type: dropdown
  id: system-type
  attributes:
    label: 系统类型 (System Type)
    description: 你在哪个系统类型下运行的 CF ？(What type of system are you running CF on?)
    options:
      - amd64
      - amd32
      - arm64
      - arm32
  validations:
    required: true
- type: dropdown
  id: cf-version
  attributes:
    label: CF 版本 ( CF Version)
    description: 你运行的是 CF 的哪个版本？(What version of our software are you running?)
    options:
      - 最新的 (Latest)
      - 0.4.x
      - 0.3.x
      - 0.2.x
      - 0.1.x
      - 0.0.x
  validations:
    required: true
- type: textarea
  attributes:
    label: 补充信息 (Anything else?)
    description: |
      链接？参考资料？任何可以给我们提供更多关于你所遇到的问题的背景资料的东西
      Links? References? Anything that will give us more context about the issue you are encountering!

      提示：你可以通过点击这个区域来突出显示它，然后将文件拖入，从而附上图片或其他文件。
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
